#+TITLE: Stun lock procrastination

One of the primary markers of ADHD is /not starting/. There are many other aspects, for sure, but often what looks like "hyperactivity" is actually just the noise getting in the way of what we /want/ to be doing but that we haven't started yet.

So when I first came across the idea of procrastination as a tool via [[https://www.structuredprocrastination.com/][structured procrastination]] years before my ADHD diagnosis it somewhat resonated... but not completely. The essay is well written, funny, and makes some good points but something felt fundamentally "off" about it when I tried to see if I could use the techniques. John Perry describes his trick as filling the top of the to do list with a certain type of task:

#+BEGIN_QUOTE
The ideal sorts of things have two characteristics, First, they seem to have clear deadlines (but really don't). Second, they seem awfully important (but really aren't).
#+END_QUOTE

He rightly points out that interacting with pretty much any organisation of any size will be stuffed full of such tasks.

This then allows him to procrastinate on the things at the top of the list by doing things that are actually more important but "less urgent". Turns out: my brain does not work like that. A sentence that I live by a little more often than is strictly comfortable.

My default state of procrastination is not the same as John Perry's; he describes a state in which he chooses to do something else, where he decides to do something different. Mine tends to fall into one of two categories:

- I do something for hours, and when I'm next interrupted I wonder "why was I even doing that?"
- I realise that I need to do something and I cannot make myself do it so I do /nothing/

And on that latter point, I really do mean /nothing/. If I know that I need to do the washing up, but I can't face it, I will "stun lock" sitting on a chair for anything from minutes to multiple hours because washing up is what I /need to do/ and the washing up is what I /cannot do/. I have lost entire days to not being able to face trivial ten minute tasks because they were the crucial thing that needed to get done, and I could not face starting them.

On the "why was I even" form of procrastination, I have to admit that the only thing I've really found helpful is good medication and trying to build at least some structure into the day - although without either the medication or outside help the structure doesn't tend to be that reliable.

But for the second kind I've slowly begun to realise that it is an experience that I can learn to recognise. It is the historical experience of beating myself up for being too lazy to do the thing that needed doing. Never mind that I wasn't actually doing what I wanted to do instead; if you blink long enough to look objectively, it would be a strange definition of laziness that included "not doing the things I want to do for hours at a time while feeling miserable." It fact, that sounds rather more like hard work to me.

By combining learning to recognise the experience with the processing I needed to do after my diagnosis, it became possible to accept it as something which is going to happen to me not because I'm intolerably lazy, but because sometimes my brain is going to find task initiation objectively difficult. The final piece of the puzzle was spotting in the research that it is very unpredictable /what/ tasks will be difficult to initiate.

Slowly, a light appeared in the depressive haze of not getting stuff done: what if, instead of trying to force myself to do /this/ thing, or trying to trick myself into doing it by "doing something fun" first, I just asked the question: "what can I do right now?" Trying to consult a to do list or be certain I'm doing something important is often a task I /can't/ do right now, so I look for tasks that are short, productive, and feel achievable without trying to check too hard if they are the /most/ important, or the /most/ urgent, of the tasks I might theoretically be able to do right now.

Turns out, it actually works pretty well. Especially because /starting/ really is the hardest bit. For example, I've written this blog post now that I've been meaning to write for weeks having promised someone I'd explain a throw away comment in a bit more detail. And once it's posted, I'm pretty sure that I've built up enough momentum that I'll be able to fill in the form that I was "supposed" to be filling in this morning as the most urgent task on the list.

And if I haven't, there's still the washing up.

