#+TITLE: Mavnn's blog

* Publishing with VisualInk
:PROPERTIES:
:ID:       7E453C3D-2A65-424C-8959-758D1DCB3ACC
:RSS_PERMALINK: 2025/11/14/visualink_milestone.html
:PUBDATE:  2025-11-14
:END:
VisualInk is my current project to work with novice coders (children, but also potentially adults as well) who are interested in story telling. It hit a big milestone today as I added the ability to publish visual novels on the platform - which is slightly more challenging than you'd think as that means threading through the ability to see assets that belong to a known user without accidentally opening up the user's underlying script files or letting people edit their content.

As a side effect, I was also able to add a feature I've been wanting from the beginning: [[https://visualink.mavnn.eu/examples/AloneInTheDark][an example mini-visual novel]] that you can play through without having to sign up or create an account. For bonus points, you can [[https://visualink.mavnn.eu/script/demo][view the script of the example]] in a fully functional editor to get a handle of how Ink works (although you can't save or run your changes unless you set up an account).

Anyway; I'm pretty chuffed about all of this. If you're interested in spreading the joy of writing interactive fiction, I'd love some more example stories to show case, and if you're interested in how my F# code for the server is evolving I'm always up for pull requests and happy to answer questions. In either case, the place to suggest things is at the [[https://github.com/mavnn/VisualInk][project repository]].

If you'd just like to comment on this milestone, then [[https://mastodon.sdf.org/@mavnn/115548826768453925][this mastodon post]] is the place to be.
* Coding games with a story
:PROPERTIES:
:ID:       26BB433F-E0DF-4CF5-88D4-1D8C3A6C0046
:RSS_PERMALINK: 2025/10/29/coding_games_with_a_story.html
:PUBDATE:  2025-10-29
:END:
A short post this time, but one that will probably lead to more content here.

I'm teaming up with the long established and trusted [[https://www.thinkersmeetup.com/][Thinkers Meetup]] to offer a course for 9-13 year old thinkers to write visual novels called [[https://www.thinkersmeetup.com/service-page/coding-games-with-a-story-ages-9-13][Coding Games with a Story]]. I'm hoping this will be the first of many!

If you know people in that age range who would in interested, or you're wondering what on earth I'm talking about, this video might help!

For those of you who have been following along for a while, you might be more interested to hear that the course is being powered by an open source website written in F#, including some code that might look very familiar from my previous "dev journals" a year or two back. If you're interested in having a look at what a full (if not huge) F# project looks like, with realistically unpolished code, the repository is at https://github.com/mavnn/VisualInk.

Got comments? This [[https://mastodon.sdf.org/@mavnn/115458607249000834][Mastodon post]] is a great place to leave them.
* Stun lock procrastination
:PROPERTIES:
:RSS_PERMALINK: 2025/09/16/stun_lock_procrastination.html
:PUBDATE:  2025-09-16
:ID:       162A7A20-55BB-426A-9804-6D8EE08C13DF
:END:
One of the primary markers of ADHD is /not starting/. There are many other aspects, for sure, but often what looks like "hyperactivity" is actually just the noise getting in the way of what we /want/ to be doing but that we haven't started yet.

So when I first came across the idea of procrastination as a tool via [[https://www.structuredprocrastination.com/][structured procrastination]] years before my ADHD diagnosis it somewhat resonated... but not completely. The essay is well written, funny, and makes some good points but something felt fundamentally "off" about it when I tried to see if I could use the techniques. John Perry describes his trick as filling the top of the to do list with a certain type of task:

#+begin_quote
The ideal sorts of things have two characteristics, First, they seem to have clear deadlines (but really don't). Second, they seem awfully important (but really aren't).
#+end_quote

He rightly points out that interacting with pretty much any organisation of any size will be stuffed full of such tasks.

This then allows him to procrastinate on the things at the top of the list by doing things that are actually more important but "less urgent". Turns out: my brain does not work like that. A sentence that I live by a little more often than is strictly comfortable.

My default state of procrastination is not the same as John Perry's; he describes a state in which he chooses to do something else, where he decides to do something different. Mine tends to fall into one of two categories:

** I do something for hours, and when I'm next interrupted I wonder "why was I even doing that?"
:PROPERTIES:
:ID:       B047B1AA-2C72-407A-A307-E9F417B73940
:END:
** I realise that I need to do something and I cannot make myself do it so I do /nothing/
:PROPERTIES:
:ID:       E596D3E5-F61C-474A-A5E8-1D741870AAA5
:END:

And on that latter point, I really do mean /nothing/. If I know that I need to do the washing up, but I can't face it, I will "stun lock" sitting on a chair for anything from minutes to multiple hours because washing up is what I /need to do/ and the washing up is what I /cannot do/. I have lost entire days to not being able to face trivial ten minute tasks because they were the crucial thing that needed to get done, and I could not face starting them.

On the "why was I even" form of procrastination, I have to admit that the only thing I've really found helpful is good medication and trying to build at least some structure into the day - although without either the medication or outside help the structure doesn't tend to be that reliable.

But for the second kind I've slowly begun to realise that it is an experience that I can learn to recognise. It is the historical experience of beating myself up for being too lazy to do the thing that needed doing. Never mind that I wasn't actually doing what I wanted to do instead; if you blink long enough to look objectively, it would be a strange definition of laziness that included "not doing the things I want to do for hours at a time while feeling miserable." In fact, that sounds rather more like hard work to me.

By combining learning to recognise the experience with the processing I needed to do after my diagnosis, it became possible to accept it as something which is going to happen to me not because I'm intolerably lazy, but because sometimes my brain is going to find task initiation objectively difficult. The final piece of the puzzle was spotting in the research that it is very unpredictable /what/ tasks will be difficult to initiate.

Slowly, a light appeared in the depressive haze of not getting stuff done: what if, instead of trying to force myself to do /this/ thing, or trying to trick myself into doing it by "doing something fun" first, I just asked the question: "what can I do right now?" Trying to consult a to do list or be certain I'm doing something important is often a task I /can't/ do right now, so I look for tasks that are short, productive, and feel achievable without trying to check too hard if they are the /most/ important, or the /most/ urgent, of the tasks I might theoretically be able to do right now.

Turns out, it actually works pretty well. Especially because /starting/ really is the hardest bit. For example, I've written this blog post now that I've been meaning to write for weeks having promised someone I'd explain a throw away comment in a bit more detail. And once it's posted, I'm pretty sure that I've built up enough momentum that I'll be able to fill in the form that I was "supposed" to be filling in this morning as the most urgent task on the list.

And if I haven't, there's still the washing up.

Thoughts? Comments? Here's a [[https://mastodon.sdf.org/@mavnn/115213753851467347][Mastodon post]] to leave them on.
* Conflict free syncthing notes
:PROPERTIES:
:ID:       0C23E268-F37F-4C6C-8E38-F04C03486EED
:RSS_PERMALINK: 2025/08/15/conflict_free_syncthing_notes.html
:PUBDATE:  2025-08-15
:END:
Just a short trick this time, mostly for my own records. As a family we've started moving to Syncthing for syncing files across devices, and "open" note taking formats like ".org" and ".md" for long term note taking. I've been using org-mode for a while personally, and now the rest of the family have been burned enough by the alternatives over the years that they're coming to similar conclusions even if not all of them want to use Emacs!

Syncthing has a sensible general purpose policy with conflicts of creating a copy of a file where a conflict exists by adding a ~.sync-conflict-<date>-<time>-<device-id>.~ pseudo-extension before the file's true extension (or to the end of the filename if it didn't have one).

In general, this is great as it means that a) all in sync devices have a shared understanding of the "winning" version of the file, and b) you can manually do any comparisons you need to and by saving a new version of the "original" file name and deleting the conflicting copies you resolve the conflict for everybody.

But with plain text note files, we can actually do a bit better than that. Because these files are always text, we can use a standard merge algorithm on them. And because the places where conflicts happen most are (almost by definition) things like todo lists and similar, we can even go a step further and specify that even if there is a line/word level conflict that the algorithm can't resolve, we can allow the resolution to be "just in line the changes from both sides."

So there's now a cron job running on the Raspberry Pi that acts as our "introducer" node in our Syncthing mesh, which looks like this:

#+begin_src bash
  #!/usr/bin/env bash
  # Find all files that are syncthing conflict markers, and have
  # a "note" extension (md or txt or org)
  readarray -t CONFLICTS < <( \
    find /syncthing/share/parent/directory -type f \
         -name "*.sync-conflict*" \
         \( -name "*.md" -o -name "*.org" -o -name "*.txt" \) \
  )
  # For each file:
  for CONFLICT in "${CONFLICTS[@]}";
  do
     # Build the regex for matching conflict files and extracting
     # the original file name.
     # 1. The marker, capturing the file name in a group.
     REG="\(.*\)sync-conflict-"
     # 2. The date
     REG+="[[:digit:]]\{8\}-"
     # 3. The time
     REG+="[[:digit:]]\{6\}-"
     # 4. The originating device ID
     REG+="[A-Z0-9]\{7\}"
     # 5. The original file extension
     REG+=".\(.*\)"
     # Find the "winning" version with the original file name
     CHOSEN="$(echo "$CONFLICT" | sed -n "s/${REG}/\1\2/p" )"
     echo Merging "$CHOSEN" "$CONFLICT"
     # If the original file actually exists (nothing stops a user from deleting it)
     if [ -f "$CHOSEN" ]; then
       # Merge the two versions of the file, taking from both in case of conflict;
       # this may cause repetition but won't lose data. Delete the conflict file
       # but only if the merge reported no errors.
       git merge-file --union \
           "$CHOSEN" "/syncthing/share/parent/directory/empty_file" \
           "$CONFLICT" && rm "$CONFLICT"
     else
       echo "No current file found"
     fi
  done
#+end_src

The only slight gotcha is you'll need to run ~touch /syncthing/share/parent/directory/empty_file~ to create an empty file to be used as the "parent" of the two conflicting versions. Extra internet points available to anyone who instead works out how to use a historical version from syncthing's archive functionality, but for me on this occasion that wasn't really needed.

Got comments or ideas? The Mastodon post for this blog can be found here: https://mastodon.sdf.org/@mavnn/115038110993820603
* A gentle introduction to Effect TS
:PROPERTIES:
:ID:       897A1F78-39B6-4704-AF2F-2A774F9B1F72
:RSS_PERMALINK: 2024/09/16/intro_to_effect_ts.html
:PUBDATE:  2024-09-16
:END:
I've recently been writing TypeScript again in a green field project, and we made the decision to
use the [[https://effect.website/][Effect]] library. It's not a small decision to make: although you can use bits of Effect in
an existing code base, its real benefit is when it is used as (to quote the website) "the missing
standard library for TypeScript".

Overall, we're happy with the choice but the learning curve has a few sharp edges and while the
[[https://effect.website/docs/introduction][docs]] aren't bad it does feel like they could do a better job of introducing the most used features
in a way that feels familiar to TypeScript developers so they can at least *read existing* Effect
code before starting to introduce the many, many, powerful features that come with the library.

This post is an attempt to do exactly that.

** The Effect type
:PROPERTIES:
:ID:       7A1A20A8-DDEC-44BD-AE51-353F04173975
:END:

The very first thing you need to understand about Effect is that it is built around a specific type.
Appropriately enough, the ~Effect~ type. This type functions as a replacement for ~Promise~, allowing
for asynchronous code, but also covers a few other needs.

Let's get started, in the traditional way:

#+begin_src typescript
  import { Effect } from "effect"

  const hello = (name?: string): Effect.Effect<string> =>
    Effect.gen(function* () {
      return `Hello, ${name || "world"}!`
    })
#+end_src

This code is spiritually the same as writing:

#+begin_src typescript
  const helloAsync = async (name?: string): Promise<string> => {
    return `Hello, ${name || "world"}!`
  }
#+end_src

You can think of the ~Effect.gen(function* () { ... })~ as a slightly more verbose version of the ~async~ prefix to a function.

What about calling the function? Again, we have a similar concept but different syntax to ~async/await~.

#+begin_src typescript
  // Effect version
  const sayHello: Effect.Effect<void> =
    Effect.gen(function* () {
      const greeting = yield* hello("world")
      yield* sendGreetings(greeting)
    })

  // Async/await version
  const sayHelloAsync: Promise<void> = {
    const greeting = await helloAsync("world")
    await sendGreetingsAsync(greeting)
  }
#+end_src

Given that we're using a cooperative scheduling system for asynchronous code, you can think of ~yield*~ as
saying "hey runtime - I'm yielding the thread now, start me back up when the effect on the right has finished."

There is, however one big difference between these two which will catch you out if you don't know about it.

** Hot and cold promises
:PROPERTIES:
:ID:       78B18CAB-4D47-4D30-8DA0-01A8EF43251F
:END:

~Promise~ is what is sometimes referred to as a "hot" or "immediate" asynchronous construct. What does that mean?

Well, in the example above ~sayHelloAsync~ is a constant value. As soon as the value is created, the logic within
the promise will be scheduled for execution and we will start the process of asynchronously running the ~helloAsync~
function. If we await the result of ~sayHelloAsync~ somewhere else, we will block until the function has finished.

This also means that if we ~await~ ~sayHelloAsync~ in two different places, we will only send greetings *once*. After
all, the ~Promise~ type that we are handing around represents the running execution of an asynchronous process; it has
already started, and awaiting it multiple times won't start it again.

~Effect~, by contrast, is a "cold" or "thunked" asynchronous construct. It represents a series of steps that /will be/
executed /if/ the result is requested.

So if we run:

#+begin_src typescript
  const camelot: Effect.Effect<void> =
    Effect.gen(function* () {
      yield* sayHello
      yield* sayHello
      yield* sayHello
    })
#+end_src

We will send the greetings three times, but only when somebody requests the result of running ~camelot~. Until
then, nothing will happen at all.

*If you remember nothing else from this post*, remember that an ~Effect~ that nobody executes never runs. This /will/ catch you
out with logging.

#+begin_src typescript
  // logs nothing
  const camelot: Effect.Effect<void> =
    Effect.gen(function* () {
      Effect.log("Bass voice: spam a looooooot")
      yield* sayHello
      yield* sayHello
      yield* sayHello
    })

  // logs the bass voice
  const camelot: Effect.Effect<void> =
    Effect.gen(function* () {
      yield* Effect.log("Bass voice: spam a looooooot")
      yield* sayHello
      yield* sayHello
      yield* sayHello
    })
#+end_src

Although the ability to create Effects without executing them can be extremely useful, leaving ~yield*~ out of
your code when you actually need it is probably the most frustrating element of learning Effect, and the one
that the compiler is least able to warn you about.

** Pipes
:PROPERTIES:
:ID:       24CB6FFF-476D-4933-8A13-C4597A71FDE9
:END:

Effect makes heavy usage of a concept it calls "pipes", which is a way of passing a value through a series of functions.

The main place you'll see this is that we can wrap ~Effect~ values in a wide variety of ways. These are very powerful,
but quickly start suffering from the "lisp effect" of a pyramid of brackets when we start combining them.

Let's rewrite the ~camelot~ function above using the built in ~Effect.repeatN~ method:

