#+TITLE: Mavnn's blog

* Log in, log out
:PROPERTIES:
:RSS_PERMALINK: 2024/03/01/dev_journal_4.html
:PUBDATE: 2024-03-01
:ID:       825AE3DE-DDC6-40EF-997F-4529BE02EF52
:END:
#+begin_quote
This post is part of the "Dev Journal" series. [[file:../../../2024/01/31/dev-journal-1.org][Part 1]] contains the series index, while the [[https://gitlab.com/mavnn/caldance/-/commits/DevJournal4?ref_type=tags][DevJournal4]] tag for the CalDance project in GitLab holds the state of the repository as described here.
#+end_quote

This is the big one: we have our first piece of event sourcing, and a bunch of infrastructure to get us there. So big, in fact, that I'm going to split the post into two and publish the remainder early next week.

A lot has changed, and I'm not going to go into every single detail so if you're following along by hand I made a pull request for the changes added here so that you can [[https://gitlab.com/mavnn/caldance/-/merge_requests/2/diffs][see them all in one place]].

** Nix pulling its weight
:PROPERTIES:
:ID:       9237AA51-026B-4A6D-A7FB-C6C917992E8D
:END:

We're about to add a database to our project, and this is an area where Nix really shines.

Adding services with pinned versions of dependencies to are development environment is as simple as adding them to the list in ~flake.nix~:

#+begin_src nix
  devShells.default = pkgs.mkShell {
    buildInputs = [
      dnc.sdk_8_0
      pkgs.nixfmt
      pkgs.skopeo
      pkgs.overmind
      pkgs.tmux
      pkgs.postgresql
      fantomas
      format-all
      format-stdin
      local_postgres
    ];
  };
#+end_src

The only clever thing we're doing here is also adding a ~local_postgres~ command which runs postgres with its data directory set to be a git ignored directory in the repository. This means that a simple git clean will reset the database along with everything else.

As a courtesy to developers who may work on code that isn't CalDance, we also set a non-standard port for postgres to use in our ~.envrc~ file so that we don't compete with any system wide installations that may already be running.

Overmind is a process runner that runs processes as defined in a ~Procfile~, so we add one to the root of the project with the following:

#+begin_src procfile
  server: dotnet watch --project Server/CalDance.Server.fsproj
  postgres: local_postgres
#+end_src

Now we can run ~overmind s~ to start both postgres and a dotnet watcher to live recompile our server code as it changes.

** Adding some nuget dependencies
:PROPERTIES:
:ID:       7EDE2A3D-CC28-4FD5-B891-53DA2158D619
:END:

We're adding dependencies to our server of [[https://martendb.io/][Marten]] (document/event database library that sits on top of postgres) and [[https://serilog.net/][Serilog]] (a nice structured log library).

Marten depends on a postgres library with native (i.e. non-dotnet) dlls, so to allow Nix to cache and link to the correct versions of the native code we have to specify which runtimes we expect to be building our code for. For the curious minded, you don't need to do this to be able to run ~dotnet build~ directly because the ~dotnet~ cli will dynamically download and add the required native libraries - which breaks Nix's caching strategy of a reproducible output from a fixed set of input files.

This isn't a huge issue once you know you need to do it; you just add a ~RuntimeIdentifiers~ node to your project files under the ~TargetFramework~ node like so:

#+begin_src xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>osx-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>
#+end_src

Then we can add our nuget packages as normal and everything continues to work:

#+begin_src xml
  <ItemGroup>
    <PackageReference Include="Falco" Version="4.0.6" />
    <PackageReference Include="Marten" Version="6.4.1" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
  </ItemGroup>
#+end_src

** Opinionated endpoint builders
:PROPERTIES:
:ID:       9D3A8FBB-D84B-4329-874A-324C5A75FCAB
:END:

In general, the code to handle an endpoint in an AspNet.Core application is a function from ~HttpContext~ to ~Task~, where we mutate the HTTP context and then write the correct output stream.

Falco gives us an abstraction a little higher than that by giving us a set of composable functions for manipulating the HTTP context, which is already a step forward. But I was finding them harder to compose than I would like because in several cases the functions took two inputs and effectively "branched" the response that could be given - for example, do I have the form fields I expect in this POST request, or am I logged in.

I quickly realized that I'd be happier with some kind of "result" mechanism - a way to be able to declare during the specification of a handler that I wanted to short circuit from this point onwards with a failure response.

I also knew that I wanted a type safe way of writing handlers for paths with "place holder" sections.

Because of that, I added a ~Routing~ in which I've defined a ~Handler~ type as below:

#+begin_src fsharp
  type Handler<'a> =
    HttpContext -> Task<HttpContext * Result<'a, HttpHandler>>
#+end_src

For the sharp eyed among you with functional programming experience you may have spotted this is the same shape as the data type of a stateful either monad, and indeed we also define a computational expression called ~handler~ that allows us to now write our handlers in a more declarative style.

The revised ~indexEndpoint~ in the main program file gives a good example of what it looks like:

#+begin_src fsharp
  let indexRoute = literalSection "/"

  let indexEndpoint =
    Handler.toEndpoint get indexRoute (fun () ->
      handler {
        let! user = User.getSessionUser

        return
          (Response.ofHtml (
            Elem.html
              []
              [ Elem.body
                  []
                  [ Elem.h1
                      []
                      [ match user with
                        | Some u ->
                          Text.raw $"Hi {u.username}!"
                        | None ->
                          Text.raw "You should go log in!" ]
                    Elem.p
                      []
                      [ Text.raw "Would you like to "
                        Elem.a
                          [ Attr.href (
                              greetingRoute.link "Bob"
                            ) ]
                          [ Text.raw "greet Bob?" ] ] ] ]
          ))
      })
#+end_src

Note the ~let!~ on the first line where we pull the user session out of the HTTP context which the computational expression is "invisibly" carrying along for us.

** Connecting up the database
:PROPERTIES:
:ID:       F3F00B6E-A3D8-4A74-81B1-6A8FF84E270F
:END:

Having defined our handler type, it makes sense to make the rest of our tooling easy to use from within the abstraction.

The new ~Marten~ module contains some boiler plate to configure Marten and add Serilog logging to it, but most importantly it also adds:

#+begin_src fsharp
  let withMarten f =
    Handler.fromCtx (fun ctx ->
      ctx.GetService<IDocumentSession>())
    |> Handler.bind (f >> Handler.returnTask)

  // Marten returns null if a record isn't found, but
  // F# records declare they can't be null. This works
  // around that to return an option instead
  let returnOption v =
    if (v |> box |> isNull) then None else Some v
#+end_src

Now from within any HTTP handler we're writing, we can write code like:

#+begin_src fsharp
  let! user =
    Marten.withMarten (fun marten ->
      marten.LoadAsync<UserRecord>(id))
#+end_src

...and as if by magic the request specific Marten session will be pulled out of the HTTP context of the request and we can use it to connect to our data source.

** To be continued...
:PROPERTIES:
:ID:       FB181539-061D-4A0A-A4F9-99652EBBC0A0
:END:

I think that's about enough for this blog post, because I want to leave a whole post for the real meat of this set of changes: our first domain entity, the ~User~.

If you want a sneak peak, you can check out the PR and see how we can define a neat vertical slice of responsibility in our code base. The module takes the responsibility for user management all the way from the domain object, the events that can happen to it, the Marten config to make sure those are tracked, through to the paths that it has responsibility for and the UI that will be displayed when they are requested. Lots of fun stuff for us to talk about in the next exciting installment of "Dev Journal": different time, multiple channels, next week.
* ADHD and TDD
:PROPERTIES:
:RSS_PERMALINK: 2024/02/21/adhd_and_tdd.html
:PUBDATE: 2024-02-21
:ID:       AEAEE3E5-F12D-4E47-A693-4D085C238A2C
:END:
#+begin_quote
This piece of writing started as repost comment on LinkedIn responding to a question from J. B. Rainsberger about [[https://www.linkedin.com/posts/jbrains_tdd-adhd-adhd-activity-7165713710492176385-xK56][how people with an ADHD diagnosis experienced TDD]]. It's a good question, but it's the kind of topic I "own" enough that I don't want to leave my thoughts on it locked away on a platform like LinkedIn, so now they're here too!
#+end_quote

This is an interesting one for me; I have both an ADHD diagnosis and I do feel that I use certain programming practices to compensate for it. Something that interests me enough that I'm talking on the subject at Lambda Days 2024, in fact.

Any practice that starts with building a feed back loop is going to be helpful from the ADHD point of view; for example, I have a strong preference for strongly typed languages because the compiler will remind me to finish bits I've forgotten about or catch the typos of concentration lapses in the wild.

That said, I'm personally not a huge fan of TDD as I've normally met it in the wild (I can see the one true Scotsman replies from here, and some of you are probably even right). And the reason for that dislike is also ADHD related but has nothing to do with the initial writing of the code - but with refactoring.

In the vast majority of cases I've seen, TDD has led to code bases with many, many, tests that are tightly coupled to the current implementation of a piece of code because what's actually happened is that each test has been written to confirm the next piece of the implementation is doing what is expected, not to test the overall inputs/outputs of the "block". Mocks that check they are called in a certain order or with certain inputs. Carefully crafted fake dependencies which return the data needed in the correct order and type to satisfy the internal of the function being tested. (Is this what TDD is meant to be? No, not at all - I'm aware)

This makes refactoring deeply painful with a pain that hits hard at the heart of ADHD - you're faced with the choice of updating all these painful, pointless, implementation internal specific mocks on the one hand or having the argument about why your refactoring PR "reduces test coverage" on the other. If you're particularly unlucky there aren't any tests covering the actual _behaviour_ of the original code at all, and now you're left wondering:

"But is my refactor really a refactor at all?"

(It would be remiss of me not to note that teaching developers how to test behaviour and not implementations is actually a service I offer, partly because I don't want to live with the consequences of them not knowing! See [[file:../../../2024/01/29/short_term_help.org][my short term consulting page]].)
* Does it run? Dev Journal 3
:PROPERTIES:
:RSS_PERMALINK: 2024/02/20/dev-journal-3.html
:PUBDATE: 2024-02-20
:ID:       659332D6-9EFD-4C29-8644-EF33259F7340
:END:
#+begin_quote
This post is part of the "Dev Journal" series. [[file:../../../2024/01/31/dev-journal-1.org][Part 1]] contains the series index, while the [[https://gitlab.com/mavnn/caldance/-/commits/DevJournal3?ref_type=tags][DevJournal3]] tag for the CalDance project in GitLab holds the state of the repository as described here.
#+end_quote

A short update this time. [[https://gitlab.com/mavnn/caldance/-/issues/3][Gregg Bremer]] (hi Gregg!) pointed out that running ~nix run~ on his linux machine resulted in an error about not being able to find ~libssl~.

This neatly highlights one of the weak spots of Nix; while an excellent packaging solution, it isn't perfect. Nix sandboxes your packages by altering the path environment variable, but not everything is located via that mechanism.

In this case, ~nix run~ ran on my machine because I happened to have the libraries in the "right place" for a self contained dotnet core executable, but Gregg did not.

Neither, it turns out, did the docker container I was building. I built and tested it initially with a dotnet console app (which did work, not needing ~libssl~) and then carried on assuming that running ~nix run~ on my local machine would also tell me if the docker image could run correctly.

I've now fixed up the code in the previous posts (we needed to add some ~runtimeDeps~ to our server package, and the docker image start up command needs to create a writable ~/tmp~ directory for asp.net to run correctly).

Most importantly though, I've also made sure that CI will prevent this from happening again by actually checking that the docker image produced can respond to a request to the index with a 200 response code. This is done by adding "stages" to our CI build; the first does exactly what we were doing already, the second then starts the just finished docker image as a "service" and uses ~curl~ to check it can respond to us.

You can check out the revised ~.gitlab-ci.yml~ file below:

#+begin_src yaml
  stages:
    - build-container
    - end-to-end-tests

  build-container:
    stage: build-container
    image:
      name: "nixos/nix:2.19.3"
    variables:
      IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    before_script:
      - nix-env --install --attr nixpkgs.skopeo
    script:
      - mkdir -p "$HOME/.config/nix"
      - echo 'experimental-features = nix-command flakes' > "$HOME/.config/nix/nix.conf"
      - mkdir -p "/etc/containers/"
      - echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
      - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      - 'nix build .#dockerImage .#test'
      - mkdir testResults
      - 'cp result-1/* testResults'
      - ls -lh ./result
      - 'skopeo inspect docker-archive://$(readlink -f ./result)'
      - 'skopeo copy docker-archive://$(readlink -f ./result) docker://$IMAGE_TAG'
    artifacts:
      when: always
      paths:
        - 'testResults/*.xml'
      reports:
        junit: 'testResults/*.xml'

  end-to-end-tests:
    stage: end-to-end-tests
    image:
      name: "nixos/nix:2.19.3"
    variables:
      IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      GIT_STRATEGY: none
    services:
      - name: $IMAGE_TAG
        alias: caldance
    script:
      - curl -f "http://caldance:5001/"
#+end_src
* Do notation for TypeScript
:PROPERTIES:
:RSS_PERMALINK: 2024/02/19/do-notation-for-typescript.html
:PUBDATE: 2024-02-19
:ID:       F0351844-9CEE-43FC-B892-9309DA63F829
:END:
This is rather an aside from recent blog posts, but something I found interesting none the less.

Fair warning to start us off: this post assumes that you are aware of and understand "do notation" (or "computational expressions" or "monad syntax") and like the idea of having it available in TypeScript.

It starts by working through a possible way of implementing a type safe representation of a sequence of monadic operations that has a much nicer user experience than nested continuation functions, and then leads into a lengthy example of both building and showing how to use a monad which I've found very useful when working in TypeScript for handling asynchronous code that needs to meaningfully respond to both successes and failures.

The idea is that we're going to go from code that looks like this:

#+begin_src typescript
  export const processLaxCallback = ({
    laxOperations,
    commands,
    localFunctions,
  }: LaxCallbackDependencies) => async (httpRequest) => {
    try {
      const laxSignatureCheck = await laxOperations.checkSignature(httpRequest)
      if(isFailure(signature)) {
        await reportError(signature)
        return
      }
      const laxContext = laxOperations.parseRequest({ httpRequest, laxSignatureCheck })
      if(isFailure(laxContext)) {
        await reportError(laxContext)
        return
      }
      // ...continued
    } catch (e) {
      // ... etc
    }
  }
#+end_src

...to code that looks more like this:

#+begin_src typescript
  export const processLaxCallback = ({
    laxOperations,
    commands,
    localFunctions,
  }: LaxCallbackDependencies) =>
    SolidChain.start<{ httpRequest: HttpRequest }, LaxCallBackState>()
      .chain("laxSignatureCheck", laxOperations.checkSignature)
      .chain("laxContext", laxOperations.parseRequest)
      // ...continued
#+end_src

If you're impatient you can jump straight to [[id:8B8152C2-E896-4933-A30E-E01276B284A8][appendix 2]] where you will find a cut and pastable code block with everything you need to play with the code in the TypeScript editor of your choice.

For the avoidance of any doubt, all the code in this blog post is available for re-use under the MIT license as list in [[id:E8C7C73E-C564-4CDE-B2D9-328AFDF256F1][appendix 3]].

** The idea
:PROPERTIES:
:ID:       D36F8EFE-F836-4EAD-AE3B-69A421A01D1C
:END:

TypeScript has one form of monad notation already - the ~await~ keyword. Unfortunately, there isn't any way to plug into the mechanism used and define your own alternative ~bind~ implementation without doing something dangerously hacky. And, frankly, the last thing your TypeScript code needs is an other sharp edge to cut yourself on.

But... what does binding a value in monad notation really do? It doesn't allow you to write code you couldn't have written anyway long hand. It allows you to give the result of a calculation in your code in name in the current scope.

So: if we consider the fact that a scope is really just a mapping from names to values, and that TypeScript allows function inputs to alter the type of their output... maybe we can do something with that?

** Defining a scope
:PROPERTIES:
:ID:       C18B91D2-25FB-4D77-AF33-418FC590FC60
:END:

A type that maps names to values is reasonably easy to define in TypeScript. It looks something like this:

#+begin_src typescript
  export type Scope<Keys extends string> = {
    [K in Keys]: any;
  };
#+end_src

We can say that anything we're willing to consider as a scope is a type that extends the type above: it will have some keys, which will all be strings, and they will map to some values, which will all be sub types of ~any~.

Now we need a type safe way to add a value to the scope.

We start with a calculated type which works out what the result of adding a value with a name to a scope should be:

#+begin_src typescript
  export type ExtendedScope<
    OldScope extends Scope<any>,
    NewField extends string,
    NewValue
  > = OldScope extends any
    ? {
        [K in keyof OldScope | NewField]: K extends NewField
          ? NewValue
          : K extends keyof OldScope
          ? OldScope[K]
          : never;
      }
    : never;
#+end_src

