#+TITLE: Mavnn's blog

* Conflict free syncthing notes
:PROPERTIES:
:RSS_PERMALINK: 2025/08/15/conflict_free_syncthing_notes.html
:PUBDATE: 2025-08-15
:ID:       94F51ABC-D223-4061-9C6D-05C7758D496A
:END:
:PROPERTIES:
:ID:       0C23E268-F37F-4C6C-8E38-F04C03486EED
:END:
Just a short trick this time, mostly for my own records. As a family we've started moving to Syncthing for syncing files across devices, and "open" note taking formats like ".org" and ".md" for long term note taking. I've been using org-mode for a while personally, and now the rest of the family have been burned enough by the alternatives over the years that they're coming to similar conclusions even if not all of them want to use Emacs!

Syncthing has a sensible general purpose policy with conflicts of creating a copy of a file where a conflict exists with a ~.sync-conflict-<date>-<time>-<device-id>.~ pseudo-extension added before the files true extension (or to the end of the filename if it didn't have one).

In general, this is great as it means that a) all in sync devices have a shared understanding of the "winning" version of the file, and b) you can manually do any comparisons you need to and by saving a new version of the "original" file name and deleting the conflicting copies you resolve the conflict for everybody.

But with plain text note files, we can actually do a bit better than that. Because these files are always text, we can use a standard merge algorithm on them. And because the places where conflicts happen most are (almost by definition) things like todo lists and similar, we can even go a step further and specify that even if there is a line/word level conflict that the algorithm can't resolve, we can allow the resolution to be "just in line the changes from both sides."

So there's now a cron job running on the Raspberry Pi that acts as our "introducer" node in our Syncthing mesh, which looks like this:

#+begin_src bash
  #!/usr/bin/env bash
  # Find all files that are syncthing conflict markers, and have
  # a "note" extension (md or txt or org)
  readarray -t CONFLICTS < <( \
    find /syncthing/share/parent/directory -type f \
         -name "*.sync-conflict*" \
         \( -name "*.md" -o -name "*.org" -o -name "*.txt" \) \
  )
  # For each file:
  for CONFLICT in "${CONFLICTS[@]}";
  do
     # Build the regex for matching conflict files and extracting
     # the original file name.
     # 1. The marker, capturing the file name in a group.
     REG="\(.*\)sync-conflict-"
     # 2. The date
     REG+="[[:digit:]]\{8\}-"
     # 3. The time
     REG+="[[:digit:]]\{6\}-"
     # 4. The originating device ID
     REG+="[A-Z0-9]\{7\}"
     # 5. The original file extension
     REG+=".\(.*\)"
     # Find the "winning" version with the original file name
     CHOSEN="$(echo "$CONFLICT" | sed -n "s/${REG}/\1\2/p" )"
     echo Merging "$CHOSEN" "$CONFLICT"
     # If the original file actually exists (nothing stops a user from deleting it)
     if [ -f "$CHOSEN" ]; then
       # Merge the two versions of the file, taking from both in case of conflict;
       # this may cause repetition but won't lose data. Delete the conflict file
       # but only if the merge reported no errors.
       git merge-file --union \
           "$CHOSEN" "/syncthing/share/parent/directory/empty_file" \
           "$CONFLICT" && rm "$CONFLICT"
     else
       echo "No current file found"
     fi
  done
#+end_src

The only slight gotcha is you'll need to run ~touch /syncthing/share/parent/directory/empty_file~ to create an empty file to be used as the "parent" of the two conflicting versions. Extra internet points available to anyone who instead works out how to use a historical version from syncthing's archive functionality, but for me on this occasion that wasn't really needed.

Got comments or ideas? The Mastodon post for this blog can be found here: https://mastodon.sdf.org/@mavnn/115038110993820603
* Types et al as accessibility tools for the ADHD brain
:PROPERTIES:
:RSS_PERMALINK: 2024/05/17/adhd_refs.html
:PUBDATE: 2024-05-17
:ID:       D26BA2C6-0975-488E-9807-F7875F090F36
:END:
:PROPERTIES:
:ID:       16B63501-8C0C-4F3A-82FA-5EE453BBBBC7
:END:
I ended up with a fair number of references for my talks at [[https://www.youtube.com/watch?v=vd1-rAIYV6I][Software You Can Love]] and [[https://www.youtube.com/watch?v=DG5gLPFKcbk][LambdaDays 2024]] on how I use various tools and techniques to compensate for my late diagnosed ADHD. The two talks are based off the same outline and slides, although the speaker having ADHD the content does vary a bit between them...

Now, the list of links!

** About ADHD
:PROPERTIES:
:ID:       A238362E-47B6-4E53-97EF-6E033B9DA6E7
:END:

"How to ADHD" has lots of material on what ADHD is, how it manifests, and what you can do about it: https://howtoadhd.com/

A paper reviewing research on working memory in adults with ADHD: https://psycnet.apa.org/record/2013-16996-001

Mads Torgersen (lead designer of C# at Microsoft) talks about his own diagnosis on the No Dogma Podcast: https://nodogmapodcast.bryanhogan.net/165-mads-torgersen-adhd/

(Bonus extra: that last link has /more/ links to more ADHD resources)

Finally, I mentioned at one point an organization tool that happens to mesh fairly well with my own variant of ADHD called SkedPal: https://skedpal.com/. You prioritize tasks in advance, and assign them to "time maps" (i.e. this times are work times, these times are home times). Then you hit the button and it suggests a calendar of tasks. I've found it useful because it allows things like "this task is important to me but it doesn't matter when it is done" and "this task isn't very important but if I'm going to do it, it needs happen by Friday" and it will suggest a sane next thing to do. And when you (inevitably) fail to actually follow the plan, you just hit the button again and it suggests a new plan based on the things you actually did rather than the things it thought you were going to do. Caveat: it's not free software, and it does charge a monthly fee.

** Evidence (or not) of my favourite programming techniques being better
:PROPERTIES:
:ID:       FA1EB009-7915-44D6-AFF1-A5AC164F8E32
:END:

Dan Luu's tour de force review of research into whether or not strong typing leads to more reliable code: https://danluu.com/empirical-pl/

Brian Marick has a well thought out post on why he's not fully convinced by property based testing: https://www.crustofcode.com/a-reluctant-rebuttal/. Most importantly he links to a paper written in /1990/ that partition testing has some issues, all of which would also apply to property based testing: https://www.site.uottawa.ca/~gvj/papers/Software%20Engineering%20IEEE%20Transactions%20on%201990%20Hamlet.pdf. It is worth noting that both Marick (about PBT), and Hamlet and Taylor (about partition testing) do state that they see use cases for these testing methods, but that they do also have concerns.

The arguments I've heard against domain driven design have tended to be more anecdotal but mostly boil down to: "you're making the code harder to understand by forcing developers to understand both the code /and/ the specialist terminology of the users at the same time."

** Going deeper on Property Based Testing
:PROPERTIES:
:ID:       79B0744E-C2E1-48CC-92A2-1804A8A9C532
:END:

I happen to be a fan of Scott Wlaschin's video and blog posts at https://fsharpforfunandprofit.com/pbt/ titled "The lazy programmer's guide to writing 1000's of tests".

Otherwise, a quick google search for "John Hughes" will net you many talks from the author of the first property based testing framework.

Fuzz testing is a related topic which somewhat overlaps, but with a different focus.

** Leaning into union types, and domain driven design
:PROPERTIES:
:ID:       C81DA2A1-2227-4085-9D45-36323FEB6DCB
:END:

I cannot over stress how amazing a book "Domain Modeling Made Functional" is (again, by Scott Wlaschin) https://pragprog.com/titles/swdddf/domain-modeling-made-functional/. There is also a talk covering the basics available at https://www.youtube.com/watch?v=MlPQ0FsPxPY.

** Pushing the boundaries on types
:PROPERTIES:
:ID:       CF5528CE-15E8-4A14-8EAB-1E1523708A26
:END:

Probably the place to start is the Idris programming language https://www.idris-lang.org/
* Short term help
:PROPERTIES:
:RSS_PERMALINK: 2024/01/29/short_term_help.html
:PUBDATE: 2024-01-29
:ID:       E073C3E3-DFE4-475F-A583-0913FB0C24F8
:END:
:PROPERTIES:
:ID:       13C93632-F856-4CE5-A937-12C264E40684
:END:
#+html_head_extra: <meta property="og:image" content="https://blog.mavnn.co.uk/images/swirl.svg" /><meta property="og:type" content="article" /><meta property="og:title" content="Short term help" /><meta property="og:url" content="https://blog.mavnn.co.uk/2024/01/29/short_term_help.html" />

#+begin_quote
Updating to avoid any disappointment: I'm currently working a longer term contract again and I'm not available for the short term services listed here. Sorry!
#+end_quote

